" Loads pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim

" Pathogen set up
filetype off
call pathogen#infect()
call pathogen#infect('unpublished/{}')
call pathogen#helptags()
filetype plugin indent on

source $HOME/.vim/vimrc_settings
source $HOME/.vim/vimrc_functions
source $HOME/.vim/vimrc_commands
source $HOME/.vim/vimrc_mappings
source $HOME/.vim/vimrc_autocmds

if &loadplugins
  source $HOME/.vim/vimrc_plugins
endif

if filereadable(".vimrc_proj")
    so .vimrc_proj
else
    if filereadable("../.vimrc_proj")
        so .vimrc_proj
    endif
endif

if filereadable("/usr/local/opt/fzf/README.md")
	set rtp+=/usr/local/opt/fzf
endif
